### ISSUE TITLE
vocab - Inconsistent behavior

### ISSUE THREAD

**Issue by mikewarot** [mikewarot/stoical#8]
According to the auto-generated file  doc/words

vocab
   Print contents of the vocabulary on top of the vocabulary stack.

if you attempt to show the words in the stoical vocabulary it fails but ONLY if you do it all in one line

stoical< vocab >
  shows the user vocabulary

stoical<
vocab
>
  shows the stoical vocabulary

I've made a branch that doesn't break like this, but I'm not sure it's the right direction to go on this.

**Comment by nomadbyte** [comment]
I believe, the `vocab` works off the `current` dictionary. So the user needs to load the `stoical<` which will make it `current`, then execute the `vocab` to list the loaded definitions.

Well, it would make sense for `vocab` to be kind of "namespaced" as any other definitions. Here, for example, we override `vocab` word in a user-vocabulary, then switch to stoical-vocabulary and execute it now in "namespaced" way -- it works as expected:

```
(0)-> 'vocab : vstack ;
redefining vocab
(0)-> vocab
stoical<
user<
(0)-> stoical<
(0)-> user< vocab >
stoical<
user<
stoical<
(0)-> >
```
So I guess the `vocab` by default also needs to work in "namespaced" way.

BTW, just caught a bug triggered by `disregard` word. Just fixed it too -- will log it and push later.

**Comment by mikewarot** [comment]
fixed in mstoical with the addition of  some new words
